<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1000" started-at="2014-04-05T00:51:42Z" finished-at="2014-04-05T00:51:43Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1000" started-at="2014-04-05T00:51:42Z" finished-at="2014-04-05T00:51:43Z">
      <class name="org.kits.trax.rest.CoverageControllerIT">
        <test-method status="FAIL" signature="bulkCreate(java.util.List)[pri:0, instance:org.kits.trax.rest.CoverageControllerIT@4eceb042]" name="bulkCreate" duration-ms="982" started-at="2014-04-04T20:51:42Z" data-provider="bulkCreateData" finished-at="2014-04-04T20:51:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[org.kits.trax.domain.Coverage@149838d9, org.kits.trax.domain.Coverage@15bc391f, org.kits.trax.domain.Coverage@784a2d5e, org.kits.trax.domain.Coverage@4de8b404, org.kits.trax.domain.Coverage@68829a91, org.kits.trax.domain.Coverage@5671db31, org.kits.trax.domain.Coverage@4ced9a4d, org.kits.trax.domain.Coverage@32d5cb0, org.kits.trax.domain.Coverage@17202871, org.kits.trax.domain.Coverage@403f1e93]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [400]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at org.kits.trax.rest.CoverageControllerIT.bulkCreate(CoverageControllerIT.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bulkCreate -->
      </class> <!-- org.kits.trax.rest.CoverageControllerIT -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
